from keyboards.client_kb import kb_client
from keyboards.client_kb import kb_client_foru
from keyboards.client_kb import kb_client_schedule
from keyboards.client_kb import kb_client_subjects
from keyboards.client_kb import kb_client_links
from keyboards.client_kb import kb_client_hometask